
services:
  db:
    image: postgres:16
    container_name: os_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: os_user
      POSTGRES_PASSWORD: os_pass
      POSTGRES_DB: os_db
    ports:
      - "5432:5432"
    volumes:
      - os_pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: os_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pourya.hm@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  os_pg_data:
